// <auto-generated />
using System;
using System.Collections.Generic;
using FactoryBrain.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace FactoryBrain.Infrastructure.Migrations
{
    [DbContext(typeof(FactoryBrainDbContext))]
    [Migration("20260927222258_AddEmbeddingMetadata")]
    partial class AddEmbeddingMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FactoryBrain.Domain.Entities.ActivityEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IsoDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<string>("TargetBn")
                        .HasColumnType("text");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerbBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("activity_events", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.AgentDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ContextSlices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Execution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Glyph")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurposeBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecentCount")
                        .HasColumnType("integer");

                    b.Property<int>("Risk")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TasksToday")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("InsightId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("RiskTier")
                        .HasColumnType("integer");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.CustomerRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("ChurnRisk")
                        .HasColumnType("double precision");

                    b.Property<int>("LastOrderDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("LtvBdt")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Department", "Category");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.FloorAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalId")
                        .HasColumnType("text");

                    b.Property<string>("BodyBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("InsightId")
                        .HasColumnType("text");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("floor_alerts", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.Insight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Finding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FindingBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("insights", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.InventoryRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AtRisk")
                        .HasColumnType("boolean");

                    b.Property<int>("DaysUntilStockout")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RecentDailyDemand")
                        .HasColumnType("double precision");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("integer");

                    b.Property<int>("ReorderQty")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.LineBoardMetric", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Bottleneck")
                        .HasColumnType("integer");

                    b.Property<int>("EfficiencyPct")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NptMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("SahActual")
                        .HasColumnType("integer");

                    b.Property<int>("SahTarget")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("WipBundles")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("line_board_metrics", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.ManualDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BodyBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Dims")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TitleBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("manual_documents", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.OrderRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DaysAgo")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalBdt")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DaysAgo");

                    b.HasIndex("Region");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.PolicyDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.ProductRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostBdt")
                        .HasColumnType("numeric");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceBdt")
                        .HasColumnType("numeric");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.QcDefect", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("DefectsTotal")
                        .HasColumnType("integer");

                    b.Property<int>("InspectedTotal")
                        .HasColumnType("integer");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MajorTotal")
                        .HasColumnType("integer");

                    b.Property<int>("MinorTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReworkTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Operation", "LineId")
                        .IsUnique();

                    b.ToTable("qc_defects", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.SensorReading", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SimTick")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SimTick");

                    b.HasIndex("Source", "EntityId");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.SupplierRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OnTimeRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.VisionResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AnomalyLabelBn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnomalyLabelEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("MachineId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("RepairStepsBn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("RepairStepsEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SampleFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("vision_results", (string)null);
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("FactoryBrain.Domain.Entities.ManualDocument", null)
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.Insight", b =>
                {
                    b.OwnsMany("FactoryBrain.Domain.Entities.EvidenceRow", "Evidence", b1 =>
                        {
                            b1.Property<string>("InsightId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Count")
                                .HasColumnType("integer");

                            b1.Property<string>("Domain")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Dictionary<string, string>>("Filter")
                                .HasColumnType("jsonb");

                            b1.PrimitiveCollection<List<string>>("PreviewIds")
                                .HasColumnType("text[]");

                            b1.HasKey("InsightId", "Id");

                            b1.ToTable("insight_evidence", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InsightId");
                        });

                    b.OwnsMany("FactoryBrain.Domain.Entities.InsightFactor", "Factors", b1 =>
                        {
                            b1.Property<string>("InsightId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LabelBn")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Magnitude")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MagnitudeBn")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InsightId", "Id");

                            b1.ToTable("insight_factors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InsightId");
                        });

                    b.OwnsOne("FactoryBrain.Domain.Entities.InsightRecommendation", "Recommendation", b1 =>
                        {
                            b1.Property<string>("InsightId")
                                .HasColumnType("text");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ActionBn")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RiskTier")
                                .HasColumnType("integer");

                            b1.Property<int>("TargetStage")
                                .HasColumnType("integer");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TitleBn")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InsightId");

                            b1.ToTable("insight_recommendations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InsightId");
                        });

                    b.Navigation("Evidence");

                    b.Navigation("Factors");

                    b.Navigation("Recommendation")
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.QcDefect", b =>
                {
                    b.OwnsMany("FactoryBrain.Domain.Entities.QcDefectWeek", "Weeks", b1 =>
                        {
                            b1.Property<string>("WeekStart")
                                .HasColumnType("text");

                            b1.Property<string>("QcDefectId")
                                .HasColumnType("text");

                            b1.Property<int>("Defects")
                                .HasColumnType("integer");

                            b1.Property<int>("Inspected")
                                .HasColumnType("integer");

                            b1.Property<int>("Major")
                                .HasColumnType("integer");

                            b1.Property<int>("Minor")
                                .HasColumnType("integer");

                            b1.Property<int>("Rework")
                                .HasColumnType("integer");

                            b1.HasKey("WeekStart", "QcDefectId");

                            b1.HasIndex("QcDefectId");

                            b1.ToTable("qc_defect_weeks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QcDefectId");
                        });

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("FactoryBrain.Domain.Entities.ManualDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
